UiNotify.emNOTIFY_GAME_INIT_FINISH = 0
UiNotify.emNOTIFY_GATEWAY_CONNECT = 1
UiNotify.emNOTIFY_GATEWAY_CONNECT_LOST = 2
UiNotify.emNOTIFY_SERVER_LIST_DONE = 3
UiNotify.emNOTIFY_SERVER_CONNECT = 4
UiNotify.emNOTIFY_SERVER_CONNECT_LOST = 5
UiNotify.emNOTIFY_SYNC_ROLE_LIST_DONE = 6
UiNotify.emNOTIFY_SYNC_PLAYER_DATA_END = 7
UiNotify.emNOTIFY_CREATE_ROLE_RESPOND = 8
UiNotify.emNOTIFY_CHANGE_PK_MODE = 9
UiNotify.emNOTIFY_CHANGE_FIGHT_STATE = 10
UiNotify.emNOTIFY_RECONNECT_FAILED = 11
UiNotify.emNOTIFY_CHANGE_PLAYER_NAME = 12
UiNotify.emNOTIFY_CHANGE_PLAYER_HP = 13
UiNotify.emNOTIFY_CHANGE_PLAYER_EXP = 14
UiNotify.emNOTIFY_CHANGE_PLAYER_LEVEL = 15
UiNotify.emNOTIFY_CHAT_NEW_MSG = 16
UiNotify.emNOTIFY_CHAT_COLOR_MSG = 17
UiNotify.emNOTIFY_SYNC_ITEM = 18
UiNotify.emNOTIFY_DEL_ITEM = 19
UiNotify.emNOTIFY_CONNECT_SERVER = 20
UiNotify.emNOTIFY_CONNECT_SERVER_END = 21
UiNotify.emNOTIFY_WND_OPENED = 22
UiNotify.emNOTIFY_WND_CLOSED = 23
UiNotify.emNOTIFY_SKILL_LEVELUP = 24
UiNotify.emNOTIFY_TEAM_UPDATE = 25
UiNotify.emNOTIFY_QUICK_TEAM_UPDATE = 26
UiNotify.emNoTIFY_SKILL_CD = 27
UiNotify.emNOTIFY_MAP_LOADED = 28
UiNotify.emNOTIFY_MAP_LEAVE = 29
UiNotify.emNoTIFY_NEW_PRIVATE_MSG = 30
UiNotify.emNoTIFY_SYNC_FRIEND_REQUEST = 31
UiNotify.emNoTIFY_SYNC_FRIEND_DATA = 32
UiNotify.emNOTIFY_SYNC_PARTNER_ADD = 33
UiNotify.emNOTIFY_SYNC_PARTNER_UPDATE = 34
UiNotify.emNOTIFY_SYNC_PARTNER_DELETE = 35
UiNotify.emNOTIFY_SYNC_PARTNER_POS = 36
UiNotify.emNOTIFY_SYNC_FLY_CHAR = 37
UiNotify.emNOTIFY_NPC_DEATH = 38
UiNotify.emNOTIFY_CHANGE_FEATURE = 39
UiNotify.emNOTIFY_UPDATE_SERVER_LIST = 40
UiNotify.emNOTIFY_ADD_SKILL = 41
UiNotify.emNOTIFY_SYNC_KIN_DATA = 42
UiNotify.emNOTIFY_SYNC_ACC_SER_INFO = 43
UiNotify.emNOTIFY_SYNC_RANK = 44
UiNotify.emNOTIFY_SYNC_BATTLEARRAY = 45
UiNotify.emNOTIFY_CHANGE_ADD_FIGHT_POWER = 46
UiNotify.emNOTIFY_CHANGE_MONEY = 47
UiNotify.emNOTIFY_UI_AUTO_HIDE = 48
UiNotify.emNOTIFY_SYNC_BOSS_DATA = 49
UiNotify.emNOTIFY_GATEWAY_HANDED = 50
UiNotify.emNOTIFY_IFLY_IAT_RESULT = 52
UiNotify.emNOTIFY_NOTIFY_PROCESS_MSG = 53
UiNotify.emNOTIFY_NOTIFY_NEW_MAIL = 54
UiNotify.emNOTIFY_SYNC_MAIL_DATA = 55
UiNotify.emNOTIFY_LOAD_RES_FINISH = 56
UiNotify.emNOTIFY_FUBEN_SECTION_PANEL = 57
UiNotify.emNOTIFY_FUBEN_TARGET_CHANGE = 59
UiNotify.emNOTIFY_CHANGE_AUTOFIGHT = 60
UiNotify.emNOTIFY_BOSS_ROB_BATTLE = 61
UiNotify.emNOTIFY_SYNC_EVERYDAY_TARGET = 62
UiNotify.emNOTIFY_UPDATE_TITLE = 63
UiNotify.emNOTIFY_CARD_PICKING = 64
UiNotify.emNOTIFY_CENTER_MSG = 65
UiNotify.emNOTIFY_UPDATE_TASK = 66
UiNotify.emNOTIFY_CHANGE_VIP_LEVEL = 66
UiNotify.emNOTIFY_SYNC_SHOP_WARE = 67
UiNotify.emNOTIFY_SHOP_BUY_RESULT = 68
UiNotify.emNOTIFY_SHOP_SELL_RESULT = 69
UiNotify.emNOTIFY_PRAY_SYNC = 70
UiNotify.emNOTIFY_PRAY_ANI_CON = 71
UiNotify.emNOTIFY_UPDATE_COLORMSG_COUNT = 72
UiNotify.emNOTIFY_ANIMATION_FINISH = 73
UiNotify.emNOTIFY_ADD_SPECIAL_STATE = 74
UiNotify.emNOTIFY_REMOVE_SPECIAL_STATE = 75
UiNotify.emNOTIFY_CHANGE_PORTRAIT = 76
UiNotify.emNOTIFY_ADD_PORTRAIT = 77
UiNotify.emNOTIFY_SYNC_BATTLE_REPORT = 78
UiNotify.emNOTIFY_GET_DEBRIS = 79
UiNotify.emNOTIFY_DEBRIS_UPDATE = 80
UiNotify.emNOTIFY_SYNC_DEBRIS_ROB_DATA = 81
UiNotify.emNOTIFY_ON_DEBRIS_CARD_AWARD = 82
UiNotify.emNOTIFY_HOME_TASK_FOLD = 83
UiNotify.emNOTIFY_MAP_EXPLORE_PANEL = 84
UiNotify.emNOTIFY_RECHARGE_PANEL = 85
UiNotify.emNOTIFY_SYNC_BATTLE_OPEN = 86
UiNotify.emNoTIFY_SYNC_COMMERCE_DATA = 87
UiNotify.emNoTIFY_SYNC_COMMERCE_HELP = 88
UiNotify.emNOTIFY_SHAPE_SHIFT = 89
UiNotify.emNOTIFY_REMOVE_SHAPE_SHIFT = 90
UiNotify.emNOTIFY_WELFARE_UPDATE = 91
UiNotify.emNOTIFY_PRIVATE_MSG_NUM_CHANGE = 92
UiNotify.emNOTIFY_STRENGTHEN_RESULT = 93
UiNotify.emNOTIFY_INSET_RESULT = 94
UiNotify.emNOTIFY_COMBINE_RESULT = 95
UiNotify.emNOTIFY_SYNC_CALENDAR_REDPOINT = 96
UiNotify.emNOTIFY_SYNC_RANKBOARD_DATA = 97
UiNotify.emNOTIFY_HELPER_GET_STRANGER = 98
UiNotify.emNOTIFY_HELPER_GET_SYNCDATA = 99
UiNotify.emNOTIFY_ACTIVITY_QUESTION_UPDATE = 100
UiNotify.emNOTIFY_MONEYTREE_RESPOND = 101
UiNotify.emNOTIFY_TASK_FINISH = 102
UiNotify.emNOTIFY_BUY_DEGREE_SUCCESS = 103
UiNotify.emNOTIFY_PARTNER_FAMILIAR_MAX = 104
UiNotify.emNOTIFY_ACHIEVEMENT_DATA_SYNC = 105
UiNotify.emNOTIFY_NEED_ACCOUT_ACTIVE = 106
UiNotify.emNOTYFY_SYNC_ITEMS_BEGIN = 107
UiNotify.emNOTYFY_SYNC_ITEMS_END = 108
UiNotify.emNOTIFY_ONCOMPOSE_CALLBACK = 109
UiNotify.emNOTIFY_ON_CLOSE_DIALOG = 110
UiNotify.emNOTIFY_PARTNER_FAMILIAR_CHANGE = 111
UiNotify.emNOTIFY_MAP_ENTER = 112
UiNotify.emNOTIFY_ACTIVE_RUNTIME_DATA = 113
UiNotify.emNOTIFY_KINGATHER_UPDATE = 114
UiNotify.emNOTIFY_GET_STAR_AWARD = 115
UiNotify.emNOTIFY_FINISH_PERSONALFUBEN = 116
UiNotify.emNOTIFY_ACTIVITY_STATE_UPDATE = 117
UiNotify.emNOTIFY_PERSONALFUBEN_TIMES_CHANGE = 118
UiNotify.emNoTIFY_PERSONALFUBEN_ANI_OVER = 119
UiNotify.emNOTIFY_MONEYTREE_DATA_UPDATE = 120
UiNotify.emNOTIFY_FORBIDDEN_OPERATION = 121
UiNotify.emNOTIFY_NEED_CLIENT_UPDATE = 122
UiNotify.emNOTIFY_ADD_SKILL_STATE = 123
UiNotify.emNOTIFY_REMOVE_SKILL_STATE = 124
UiNotify.emNOTIFY_CLOSE_TO_NCP = 125
UiNotify.emNOTIFY_CHANGE_CAMP = 126
UiNotify.emNOTIFY_RECORD_BEGIN = 127
UiNotify.emNOTIFY_RECORD_END = 128
UiNotify.emNOTIFY_VOICE_RECORD_VOLUME_CHANG = 129
UiNotify.emNOTIFY_VOICE_PLAY_VOLUME_CHANG = 130
UiNotify.emNOTIFY_VOICE_PLAY_START = 131
UiNotify.emNOTIFY_VOICE_PLAY_END = 132
UiNotify.emNOTIFY_FIGHT_POWER_CHANGE = 133
UiNotify.emNOTIFY_DROP_ITEM_TYPE = 134
UiNotify.emNOTIFY_UPDATE_JUBAOPEN = 135
UiNotify.emNOTIFY_SYNC_KIN_BATTLE_DATA = 136
UiNotify.emNOTIFY_SWEEP_OVER = 137
UiNotify.emNOTIFY_TEAM_BATTLE_KILL_INFO = 138
UiNotify.emNOTIFY_TEAM_BATTLE_TIME = 139
UiNotify.emNOTIFY_FACTION_TOP_CHANGE = 140
UiNotify.emNOTIFY_TEAM_BATTLE_HIDE_SCORE = 141
UiNotify.emNOTIFY_DYN_CHANNEL_CHANGE = 142
UiNotify.emNOTIFY_SHOW_DIALOG = 143
UiNotify.emNOTIFY_PG_INIT = 144
UiNotify.emNOTIFY_PG_CLOSE = 145
UiNotify.emNOTIFY_PG_PARTNER_DEATH = 146
UiNotify.emNOTIFY_PG_PARTNER_NPC_CHANGE = 147
UiNotify.emNOTIFY_PG_PARTNER_SWITCH_GROUP = 148
UiNotify.emNOTIFY_MISSION_AWARD_ONRESULT = 149
UiNotify.emNOTIFY_MISSION_AWARD_UPDATE = 150
UiNotify.emNOTIFY_TASK_HAS_CHANGE = 151
UiNotify.emNOTIFY_UPDATE_FUBEN_SCROE = 152
UiNotify.emNOTIFY_QYHLEFT_INFO_UPDATE = 153
UiNotify.emNOTIFY_LOGINAWARDS_CALLBACK = 154
UiNotify.emNOTIFY_CHANGE_ACTION_MODE = 155
UiNotify.emNOTIFY_NEED_ACCOUT_REG = 156
UiNotify.emNOTIFY_FORBIDDEN_PARTNER = 157
UiNotify.emNOTIFY_SYN_MAP_ALL_POS = 158
UiNotify.emNOTIFY_MS_ITEM_LIST_CHANGE = 159
UiNotify.emNOTIFY_MS_MY_ITEM_LIST_CHANGE = 160
UiNotify.emNOTIFY_LOGIN_QUEUE_NOTIFY = 161
UiNotify.emNOTIFY_LOGIN_HAND_SHAKE_END = 162
UiNotify.emNOTIFY_FAKE_JOYSTICK_GUIDING = 163
UiNotify.emNOTIFY_FAKE_JOYSTICK_STATE = 164
UiNotify.emNOTIFY_SYNC_AUCTION_DATA = 165
UiNotify.emNOTIFY_FUBEN_STOP_ENDTIME = 166
UiNotify.emNOTIFY_VALUE_COMPOSE_FINISH = 167
UiNotify.emNOTIFY_SYNC_PLAYER_SET_POS = 168
UiNotify.emNOTIFY_SYNC_KIN_TRAIN_MAT = 169
UiNotify.emNOTIFY_LOGIN_SERVER_UNAVAILABLE = 170
UiNotify.emNOTIFY_UPDATE_SURVEY_STATE = 171
UiNotify.emNOTIFY_SYNC_NEARBY_TEAMS = 172
UiNotify.emNOTIFY_CHANGE_SIT = 173
UiNotify.emNOTIFY_SYNC_DATA = 175
UiNotify.emNOTIFY_GROUP_INFO = 176
UiNotify.emNOTIFY_ONHOOK_GET_EXP_FINISH = 177
UiNotify.emNOTIFY_REDBAG_DATA_REFRESH = 178
UiNotify.emNOTIFY_REDBAG_SINGLE_UPDATE = 179
UiNotify.emNOTIFY_SEND_GIFT_SUCCESS = 180
UiNotify.emNOTIFY_SYN_GIFT_DATA_FINISH = 181
UiNotify.emNOTIFY_MS_ITEM_SOLD = 182
UiNotify.emNoTIFY_FUBEN_PROGRESS_REFRESH = 183
UiNotify.emNOTIFY_LOGIN_SERVER_FAIL = 184
UiNotify.emNOTIFY_CHAT_ROOM_STATUS = 185
UiNotify.emNOTIFY_SYNC_QQ_BULUO_URL = 186
UiNotify.emNOTIFY_ON_HOME_TASK_FOLD = 187
UiNotify.emNOTIFY_SHOWTEAM_NO_TASK = 188
UiNotify.emNOTIFY_REFRESH_MESSAGE_BOX = 189
UiNotify.emNOTIFY_SUPPLEMENT_RSP = 190
UiNotify.emNOTIFY_EQUIP_MAKE_RSP = 191
UiNotify.emNOTIFY_LEADER_INFO_CHANGE = 192
UiNotify.emNOTIFY_SURVEY_SEL_INPUT_CHANGE = 193
UiNotify.emNOTIFY_MARKET_STALL_REFRESH_ALL = 194
UiNotify.emNOTIFY_CHUAN_GONG_SEND_ONE = 195
UiNotify.emNOTIFY_FORBID_STATE_CHANGE = 196
UiNotify.emNOTIFY_UPDATE_QQ_VIP_INFO = 197
UiNotify.emNOTIFY_NEW_REDBAG = 198
UiNotify.emNOTIFY_PARTNER_REINITDATA = 199
UiNotify.emNOTIFY_UPDATE_PLAT_FRIEND_INFO = 200
UiNotify.emNOTIFY_ONSYNC_NEWINFORMATION = 201
UiNotify.emNOTIFY_ONACTIVITY_STATE_CHANGE = 202
UiNotify.emNOTIFY_GUIDE_RANGE_CHANGE = 203
UiNotify.emNOTIFY_MS_GET_AVG_PRICE = 204
UiNotify.emNOTIFY_SHARE_PHOTO = 205
UiNotify.emNOTIFY_PARTNER_GRADE_LEVELUP = 206
UiNotify.emNOTIFY_ONSYNC_MONKEY = 207
UiNotify.emNOTIFY_PLAT_SHARE_RESULT = 208
UiNotify.emNOTIFY_PANDORA_REFRESH_ICON = 209
UiNotify.emNOTIFY_ONSYNC_DOMAIN_REPORT = 210
UiNotify.emNOTIFY_ONSYNC_DOMAIN_SUPPLY = 211
UiNotify.emNOTIFY_ONSYNC_DOMAIN_BASE = 212
UiNotify.emNOTIFY_ONSYNC_LEVEL_RANK = 213
UiNotify.emNOTIFY_CHAT_DEL_PRIVATE = 214
UiNotify.emNOTIFY_PRECISE_CAST = 215
UiNotify.emNOTIFY_PRECISE_TOUCH_UP = 216
UiNotify.emNOTIFY_ONLINE_ONHOOK_STATE = 217
UiNotify.emNOTIFY_CHANGE_SAVE_BATTERY_MODE = 218
UiNotify.emNOTIFY_SYN_ARENA_DATA = 219
UiNotify.emNOTIFY_SYN_ARENA_APPLY_DATA = 220
UiNotify.emNOTIFY_SYN_ARENA_DMAGE_DATA = 221
UiNotify.emNOTIFY_SYN_ARENA_TIME_DATA = 222
UiNotify.emNOTIFY_SYN_PLAYER_APPLY_ARENA_DATA = 223
UiNotify.emNOTIFY_REFRESH_WATCH = 224
UiNotify.emNOTIFY_REFRESH_QYH_BTN = 225
UiNotify.emNOTIFY_CHANGE_FIGHTPARTNER_ID = 226
UiNotify.emNOTIFY_REFRESH_QYH_BTN_TEXIAO = 227
UiNotify.emNOTIFY_TS_REFRESH_STUDENT_LIST = 228
UiNotify.emNOTIFY_TS_REFRESH_APPLY_LIST = 229
UiNotify.emNOTIFY_TS_REFRESH_TARGET_WITH = 230
UiNotify.emNOTIFY_TS_REFRESH_OTHER_STATUS = 231
UiNotify.emNOTIFY_TS_REFRESH_MAIN_INFO = 232
UiNotify.emNOTIFY_TS_REFRESH_TEACHER_LIST = 233
UiNotify.emNOTIFY_DMG_RANK_UPDATE = 234
UiNotify.emNOTIFY_XGSDK_CALLBACK = 235
UiNotify.emNoTIFY_RENOWN_SHOP_REFRESH = 236
UiNotify.emNOTIFY_EQUIP_EVOLUTION = 237
UiNotify.emNOTIFY_EQUIP_TRAIN_ATTRIB = 238
UiNotify.emNOTIFY_IMPERIAL_TOMB_BOSS_STATUS = 239
UiNotify.emNOTIFY_PRIVILEGE_CALLBACK = 240
UiNotify.emNOTIFY_DATI_DATA_CHANGE = 241
UiNotify.emNOTIFY_SEND_BLESS_CHANGE = 242
UiNotify.emNOTIFY_SET_PLAYER_NAME = 243
UiNotify.emNOTIFY_SKILL_USE_POINT = 244
UiNotify.emNOTIFY_INDIFFER_BATTLE_FACTION = 245
UiNotify.emNOTIFY_INDIFFER_BATTLE_UI = 246
UiNotify.emNOTIFY_CHANG_ROLE_WARN = 247
UiNotify.emNOTIFY_WEEKEND_QUIZ_SYN = 248
UiNotify.emNOTIFY_CHAT_THEME_OVERDUE = 249
UiNotify.emNOTIFY_ADD_SKILL_SLOT = 250
UiNotify.emNOTIFY_REMOVE_SKILL_SLOT = 251
UiNotify.emNOTIFY_NO_OPERATE_UPDATE = 252
UiNotify.emNOTIFY_CHAT_CROSS_HOST = 253
UiNotify.emNOTIFY_WISHACT_DATA_CHANGED = 254
UiNotify.emNOTIFY_BREAK_GENERALPROCESS = 255
UiNotify.emNOTIFY_AUTO_SKILL_CHANGED = 256
UiNotify.emNOTIFY_UPDATE_RECALL_LIST = 257
UiNotify.emNOTIFY_UPDATE_RECALL_COUNT = 258
UiNotify.emNOTIFY_UPDATE_RECALL_BUTTON = 259
UiNotify.emNOTIFY_ON_USE_ITEM = 260
UiNotify.emNOTIFY_PG_PARTNER_AWARENESS = 261
UiNotify.emNOTIFY_QINGRENJIE_TEXIAO = 262
UiNotify.emNOTIFY_MS_HAS_LOWER_PRICE = 263
UiNotify.emNOTIFY_LEVELUP_ASK4HELP_RSP = 264
UiNotify.emNOTIFY_WOMAN_SYNDATA = 265
UiNotify.emNOTIFY_CLICKOBJ = 266
UiNotify.emNOTIFY_REPOBJSIMPLETAP = 267
UiNotify.emNOTIFY_REPOBJLONGTAPSTART = 268
UiNotify.emNOTIFY_REPOBJTOUCHUP = 269
UiNotify.emNOTIFY_PUT_DECORATION = 270
UiNotify.emNOTIFY_SYNC_FURNITURE = 271
UiNotify.emNOTIFY_SYNC_HOUSE_ACCESS = 272
UiNotify.emNOTIFY_SYNC_MAKE_FURNITURE = 273
UiNotify.emNOTIFY_SYNC_SWITCH_PLACE = 274
UiNotify.emNOTIFY_SYNC_HOUSE_INFO = 275
UiNotify.emNOTIFY_DELETE_DECORATION = 276
UiNotify.emNOTIFY_ZHEN_YUAN_MAKE = 277
UiNotify.emNOTIFY_ROOMER_CHECKIN = 278
UiNotify.emNOTIFY_ROOMER_CHECKOUT = 279
UiNotify.emNOTIFY_SYNC_FRIEND_PLANT = 280
UiNotify.emNOTIFY_SYNC_PLANT = 281
UiNotify.emNOTIFY_PLANT_CURE_FINISHED = 282
UiNotify.emNOTIFY_HOUSE_LEVELUP = 283
UiNotify.emNOTIFY_SYNC_HOUSE_FRIEND_LIST = 284
UiNotify.emNOTIFY_SYNC_MAP_FURNITURE = 285
UiNotify.emNOTIFY_SYNC_HAS_HOUSE = 286
UiNotify.emNOTIFY_GATEWAY_LOGIN_RSP = 287
UiNotify.emNOTIFY_ARBOR_CURE_OK = 288
UiNotify.emNOTIFY_BEAUTY_VOTE_AWARD = 289
UiNotify.emNOTIFY_BEAUTY_FRIEND_LIST = 290
UiNotify.emNOTIFY_SYNC_EXT_COMFORTLEVEL = 291
UiNotify.emNOTIFY_SYNC_WEATHER_CHANGE = 292
UiNotify.emNOTIFY_DECORATION_CHANGE = 293
UiNotify.emNOTIFY_FUBEN_TARGET_CHANGE_CLOSE = 294
UiNotify.emNOTIFY_WEDDING_DRESS_CHANGE = 295
UiNotify.emNOTIFY_SYNC_XUEWEI_LEVELUP = 296
UiNotify.emNOTIFY_SYNC_LOTTERY_DATA = 297
UiNotify.emNOTIFY_SYNC_WEDDING_WELCOME = 298
UiNotify.emNOTIFY_SYNC_WEDDING_SCHEDULE = 299
UiNotify.emNOTIFY_WEDDING_CASHGIFT_CHANGE = 300
UiNotify.emNOTIFY_SYNC_WEDDING_MAP = 301
UiNotify.emNOTIFY_WEDDING_DATE_SELECT_FINISH = 302
UiNotify.emNOTIFY_FUBEN_TARGET_CHANGE_WEDDING_BTN = 303
UiNotify.emNOTIFY_SYNC_VIEW_RELATION = 304
UiNotify.emNOTIFY_CLICK_LINK_NPC = 305
function UiNotify:Init()
  self.tbCallback = {}
end
if not UiNotify.tbCallback then
  UiNotify:Init()
end
function UiNotify:RegistNotify(nEvent, fnProc, tbTable)
  assert(tbTable, string.format("nEvent:%s,", tostring(nEvent)))
  assert(nEvent, string.format("UiGroup:%s, nEvent:%s,", tostring(tbTable.UI_NAME), tostring(nEvent)))
  assert(fnProc)
  local tbCallback = self.tbCallback[nEvent]
  if not tbCallback then
    tbCallback = {}
    self.tbCallback[nEvent] = tbCallback
  elseif tbCallback[tostring(tbTable)] then
    Log(debug.traceback())
    return
  end
  if type(tbTable) == "table" then
    tbCallback[tostring(tbTable)] = {tbSelf = tbTable, fnProc = fnProc}
  end
end
function UiNotify:UnRegistNotify(nEvent, tbTable)
  local tbCallback = self.tbCallback[nEvent]
  if tbCallback and tbCallback[tostring(tbTable)] then
    tbCallback[tostring(tbTable)] = nil
  else
    print("UiNotify:UnRegistNotify", nEvent, tbTable.UI_NAME or tostring(tbTable))
  end
end
function UiNotify.OnNotify(nEvent, ...)
  local arg = {
    ...
  }
  if UiNotify.tbCallback[nEvent] then
    for szKey, tb in pairs(UiNotify.tbCallback[nEvent]) do
      local szUiName = tb.tbSelf.UI_NAME
      if not szUiName or Ui:WindowVisible(szUiName) == 1 then
        tb.fnProc(tb.tbSelf, unpack(arg))
      end
    end
  end
end
