QunYingHui.tbDefInfo = QunYingHui.tbDefInfo or {}
local tbDef = QunYingHui.tbDefInfo
tbDef.szDegreeDay = "QunYingHuiDay"
tbDef.nSaveGroupID = 24
tbDef.nSaveWinCount = 5
tbDef.nSaveTotalJoin = 6
tbDef.nSaveDayTime = 7
tbDef.nSaveLastPK1 = 8
tbDef.nSaveJiFen = 9
tbDef.nSaveDayWin = 10
tbDef.nUpdateDmgTime = 1
tbDef.nPrepareTempMapID = 1008
tbDef.fPlayerToNpcDmg = 0.1
tbDef.nGameTempMapID = 1009
tbDef.tbPrepareMapPos = {
  [1] = {2818, 6770},
  [2] = {2746, 4812},
  [3] = {6996, 6777},
  [4] = {7025, 4638}
}
tbDef.tbGameMapPos = {
  [1] = {2158, 3097},
  [2] = {2164, 1199}
}
tbDef.nMinLevel = 80
tbDef.nStartTimeMatch = 180
tbDef.nPerTimeMatch = 150
tbDef.fDefWinRate = 0.5
tbDef.nMatchPlayerCount = 2
tbDef.nPrepareGameTime = 10
tbDef.nFightGameTime = 100
tbDef.nPartnerPos = 4
tbDef.nGameEndKickOutMapTime = 6
tbDef.nWinCountNotice = 6
tbDef.nTotalMatchCount = 10
tbDef.szWorldNotice = "「%s」在群英会中获得了%s场全胜！"
tbDef.szAchievementKey = "QunYingHui_1"
tbDef.nWinJiFen = 2
tbDef.nFailJiFen = 1
tbDef.MailConent = "恭喜你在今天的群英会中，累计达到 [FFFE0D]%s[-] 积分，对应获得以下奖励"
tbDef.nTotalExtRate = 10000
tbDef.szWorldExtNotice = "「%s」在群英会中获得了%s，真是鸿运当头啊"
