HeroChallenge.tbDefInfo = HeroChallenge.tbDefInfo or {}
local tbDef = HeroChallenge.tbDefInfo
tbDef.szHeroChallengeCount = "HeroChallenge"
tbDef.nChallengTypeNone = 0
tbDef.nChallengTypeNpc = 1
tbDef.nChallengTypePlayer = 2
tbDef.nSaveGroupID = 43
tbDef.nSavePerTime = 1
tbDef.nSaveFloorCount = 2
tbDef.nSaveChallenge = 3
tbDef.nSaveChallengeRank = 4
tbDef.nSaveChallRankType = 5
tbDef.nSaveDegreeCount = 6
tbDef.nSaveDegreeDay = 7
tbDef.nSaveOneExtAward = 8
tbDef.nSaveGetAwardFlag = 9
tbDef.nSaveShowGroupID = 44
tbDef.nSaveShowFloor = 1
tbDef.nSaveShowFloorEnd = 12
tbDef.szDayUpdateTime = "4:00"
tbDef.nMinPlayerLevel = 30
tbDef.nFightMapID = 1015
tbDef.tbEnterMapPos = {1900, 2450}
tbDef.szOpenTimeFrame = "OpenDay2"
tbDef.tbFloorAchievement = {
  [1] = "HeroChallenge_1",
  [6] = "HeroChallenge_2",
  [10] = "HeroChallenge_3"
}
